name: base-login-server   

services:
  app:
    build: .
    container_name: base-login-backend 
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      API_PREFIX: ${API_PREFIX}
      API_VERSION: ${API_VERSION}
      CORS_ORIGIN: ${CORS_ORIGIN}
      THROTTLE_TTL: ${THROTTLE_TTL}
      THROTTLE_LIMIT: ${THROTTLE_LIMIT}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      DEFAULT_ROLE: ${DEFAULT_ROLE}
      NODE_ENV: ${NODE_ENV:-development}
      DB_SSL_REJECT_UNAUTHORIZED: ${DB_SSL_REJECT_UNAUTHORIZED:-false}
    restart: unless-stopped